/* Generated by Nim Compiler v0.10.1 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jonathan/Nimrod/git-source/lib -o /home/jonathan/nimrod-stuff/nimdown/nimcache/nimdown.o /home/jonathan/nimrod-stuff/nimdown/nimcache/nimdown.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <stdlib.h>
N_NIMCALL(NI, main_88003)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimdownInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimdownDatInit)(void);
extern TFrame* frameptr_16042;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16042 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16042;
	frameptr_16042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16042 = (*frameptr_16042).prev;
}

N_NIMCALL(NI, main_88003)(void) {
	NI result;
	nimfr("main", "nimdown.nim")
	result = 0;
	nimln(2, "nimdown.nim");
	result = 0;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	nimdownDatInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	nimdownInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, nimdownInit)(void) {
	nimfr("nimdown", "nimdown.nim")
	nimln(4, "nimdown.nim");
	{
		NI LOC5;
		if (!NIM_TRUE) goto LA3;
		nimln(5, "nimdown.nim");
		nimln(5, "nimdown.nim");
		LOC5 = 0;
		LOC5 = main_88003();
		exit(LOC5);
	}
	LA3: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimdownDatInit)(void) {
}

